import type { Metadata } from "next";
import "./globals.css";
import { auth } from "@/sever/auth";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "sonner";
import Navcom from "./components/Navcom";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Snap-Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const seccion = await auth();
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />
      </head>
      <body className="min-h-full w-full flex flex-col">
        <SessionProvider>
          <Navcom user={seccion?.user} expires={seccion?.expires!} />
          <Toaster />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
