import type { Metadata } from "next";
import "./globals.css";
import { auth } from "@/sever/auth";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "sonner";
import Navcom from "./components/Navcom";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import "@fortawesome/fontawesome-free/css/all.min.css";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Snap-Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const seccion = await auth();
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, viewport-fit=cover"
        />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className="min-h-full w-full flex flex-col">
        <SessionProvider>
          <Navcom user={seccion?.user} expires={seccion?.expires!} />
          <Toaster />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
